#!/bin/bash
# Cloud Deployment Script for AI Inventory Management System
# This script helps set up the cloud infrastructure

echo "🚀 AI Inventory Management System - Cloud Deployment"
echo "=================================================="

# Check if required tools are installed
command -v git >/dev/null 2>&1 || { echo "❌ Git is required but not installed. Aborting."; exit 1; }
command -v node >/dev/null 2>&1 || { echo "❌ Node.js is required but not installed. Aborting."; exit 1; }
command -v python >/dev/null 2>&1 || { echo "❌ Python is required but not installed. Aborting."; exit 1; }

echo "✅ Prerequisites check passed"

# Step 1: Supabase Setup
echo ""
echo "📊 Step 1: Supabase Database Setup"
echo "-----------------------------------"
echo "1. Go to https://supabase.com"
echo "2. Create a new account or sign in"
echo "3. Click 'New Project'"
echo "4. Choose free tier and select a region"
echo "5. Wait for project creation (~2 minutes)"
echo "6. Go to SQL Editor and run the contents of database/schema.sql"
echo "7. Go to Settings → Database → Copy the PostgreSQL URL"
echo ""
read -p "Enter your Supabase PostgreSQL URL: " SUPABASE_URL
if [ -z "$SUPABASE_URL" ]; then
    echo "❌ Supabase URL is required"
    exit 1
fi

# Step 2: Firebase Setup
echo ""
echo "🔥 Step 2: Firebase Authentication Setup"
echo "----------------------------------------"
echo "1. Go to https://console.firebase.google.com/"
echo "2. Create a new project or select existing"
echo "3. Enable Authentication → Email/Password provider"
echo "4. Go to Project Settings → General tab"
echo ""
read -p "Enter Firebase API Key: " FIREBASE_API_KEY
read -p "Enter Firebase Auth Domain (project.firebaseapp.com): " FIREBASE_AUTH_DOMAIN
read -p "Enter Firebase Project ID: " FIREBASE_PROJECT_ID

if [ -z "$FIREBASE_API_KEY" ] || [ -z "$FIREBASE_AUTH_DOMAIN" ] || [ -z "$FIREBASE_PROJECT_ID" ]; then
    echo "❌ All Firebase credentials are required"
    exit 1
fi

# Step 3: OpenRouter API Key
echo ""
echo "🤖 Step 3: OpenRouter AI Setup"
echo "------------------------------"
echo "1. Go to https://openrouter.ai/"
echo "2. Sign up for a free account"
echo "3. Get your API key from the dashboard"
echo ""
read -p "Enter your OpenRouter API Key (or press Enter to skip): " OPENROUTER_KEY

# Step 4: Railway Deployment
echo ""
echo "🚂 Step 4: Railway Backend Deployment"
echo "-------------------------------------"
echo "1. Go to https://railway.app"
echo "2. Sign up and connect your GitHub account"
echo "3. Click 'New Project' → 'Deploy from GitHub repo'"
echo "4. Select this repository"
echo "5. Railway will auto-detect Python and deploy"
echo "6. Add these environment variables in Railway:"
echo ""
echo "DATABASE_URL=$SUPABASE_URL"
echo "OPENROUTER_API_KEY=$OPENROUTER_KEY"
echo "OPENROUTER_MODEL=deepseek/deepseek-chat:free"
echo "FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID"
echo "FRONTEND_URL=https://your-vercel-app.vercel.app"
echo "AUTH_MODE=firebase"
echo "ENVIRONMENT=production"
echo "CLOUD_PLATFORM=railway"
echo "PORT=8000"
echo ""
read -p "Enter your Railway backend URL (after deployment): " RAILWAY_URL

# Step 5: Vercel Deployment
echo ""
echo "▲ Step 5: Vercel Frontend Deployment"
echo "------------------------------------"
echo "1. Go to https://vercel.com"
echo "2. Sign up and connect your GitHub account"
echo "3. Click 'New Project' → Import this repository"
echo "4. Vercel will auto-detect Next.js"
echo "5. Add these environment variables in Vercel:"
echo ""
echo "NEXT_PUBLIC_API_URL=$RAILWAY_URL"
echo "NEXT_PUBLIC_FIREBASE_API_KEY=$FIREBASE_API_KEY"
echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN"
echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID"
echo "NEXT_PUBLIC_AUTH_MODE=firebase"
echo ""

# Create production environment file
echo ""
echo "📝 Creating production environment file..."
cat > .env.production << EOF
# Production Environment Configuration
# Generated by deploy.sh script

# Database
DATABASE_URL=$SUPABASE_URL
CLOUD_PLATFORM=supabase
ENVIRONMENT=production

# AI Service
OPENROUTER_API_KEY=$OPENROUTER_KEY
OPENROUTER_MODEL=deepseek/deepseek-chat:free

# Firebase Configuration
FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID

# Frontend Configuration
NEXT_PUBLIC_FIREBASE_API_KEY=$FIREBASE_API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
NEXT_PUBLIC_API_URL=$RAILWAY_URL
FRONTEND_URL=https://your-vercel-frontend.vercel.app

# Authentication
AUTH_MODE=firebase

# Application
PORT=8000
EOF

echo "✅ Production environment file created: .env.production"
echo ""
echo "🎉 Cloud deployment setup complete!"
echo ""
echo "📋 Next Steps:"
echo "1. Complete Railway deployment with the environment variables shown above"
echo "2. Complete Vercel deployment with the environment variables shown above"
echo "3. Update FRONTEND_URL in Railway with your actual Vercel URL"
echo "4. Test your deployed application!"
echo ""
echo "🔗 Your app will be available at:"
echo "   Frontend: https://your-vercel-app.vercel.app"
echo "   Backend API: $RAILWAY_URL"
echo ""
echo "🤖 AI Agent Features:"
echo "   - Admin-only access to AI assistant"
echo "   - Can create/update products and orders"
echo "   - Full CRUD operations with authentication"
echo ""
echo "📞 Support: Check Railway/Vercel logs if deployment fails"